### ISSUE TITLE
The GraphKeys.GLOBAL_VARIABLES collection lacks some variables?

### ISSUE THREAD

**Issue by WangJerry95** [soloice/mnist-bn#2]
Hello! Thank you for the code which is very helpful to me. 
But I observed something weird. After the graph is build, I add  `variable_to_restore = slim.get_model_variables() `  to get the model's variables, and this is what I get:
![screenshot from 2018-05-28 21-27-50](https://user-images.githubusercontent.com/33449585/40616760-b6313244-62be-11e8-9b40-8be009a1400e.png)
I wonder why the **biases for convolutional&fc layers and γ for batch normalization** are nowhere to be found? By the way, if I don't use batch normalization, that is, comment out the normalization_fn part in arg_scope, the biases  will appear in the collection. 
Thanks!

**Comment by soloice** [comment]
> biases not found when combined with BN

If you use BN, typically `bias` term is omitted, because subtracting `beta` will cancel the effects of your `bias` variables. If I recall correctly, the BN paper mentioned this.
> `gamma` for BN not found

This is kind of weird. I'll look into this later.
