### ISSUE TITLE
Updating operations w/ slim.learning.create_train_op

### ISSUE THREAD

**Issue by MRLoghmani** [soloice/mnist-bn#4]
I am confused about the manual dependency established between the op "cross_entropy" and "update_op". I thought "slim.learning.create_train_op" would automatically gather the variables and update them with the training operation. 

In practice, I'm asking: why is this piece of code necessary?

```
    update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS)
    if update_ops:
        updates = tf.group(*update_ops)
        cross_entropy = control_flow_ops.with_dependencies([updates], cross_entropy)
```

I thought the conclusion of the [issue](https://github.com/tensorflow/tensorflow/issues/7469) you opened on this topic was that it's not necessary when using "slim.learning.create_train_op" .

**Comment by soloice** [comment]
Thanks for your attention. Maybe you are right.
You may test it and make a PR. I'm willing to merge it.
Sorry for my late reply.
